server:
  port: 10002             #消费者服务端口

spring:
  application:
    name: eureka-consumer    #消费者服务名
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    #消费服务访问的地址